USE Cobsystems_Base8

DROP TABLE IF EXISTS #IMP19RED

SELECT  I.COD_CRED,ARQ_IMP, CONVERT(VARCHAR,I.DATA_IMP,20) AS INICIO_IMPORTACAO, CONVERT(VARCHAR,I.DATA_FIM_IMP,20) AS FIM_IMPORTACAO,
	S.DESCRICAO, COUNT(DISTINCT H.COD_TIT) AS CONTRATOS, COUNT (DISTINCT H.COD_PARC) AS PARCELAS
INTO #IMP19RED
FROM VSQL10.COBSYSTEMS_BASE8.DBO.IMPORTACAO_HISTORICO H
	INNER JOIN IMPORTACAO_SITUACAO AS S ON H.COD_SITUACAO = S.COD_SITUACAO
	INNER JOIN IMPORTACAO I ON I.COD_IMP = H.COD_IMP
WHERE I.ARQ_IMP LIKE '%se01%' AND I.DATA_IMP BETWEEN CAST(DATEADD(day,0, GETDATE()) AS DATE) AND CAST(GETDATE()+1 AS DATE) AND I.ARQ_IMP LIKE '%EXC_RED%'
GROUP BY I.COD_CRED, I.ARQ_IMP, I.DATA_IMP, I.DATA_FIM_IMP, S.DESCRICAO
ORDER BY I.DATA_IMP DESC 

/* DECLARAÇÃO DAS VARIAVEIS*/
DECLARE
	@ARQMOV AS varchar(MAX), -- ARQUIVO DE MOVIMENTACAO
	@iNICIO AS SMALLDATETIME, --INICIO DA IMPORTACAO
	@FIM AS SMALLDATETIME, -- FIM DA IMPORTACAO
	@DEVOLUCAOCONTRATO AS INT,--QNT DE DEVOLUCAO POR CONTRATOS
	@DEVOLUCAOPARCELAS AS INT--QNT DE DEVOLUCAO POR PARCELAS

	
	SET @ARQMOV = (SELECT TOP 1 ARQ_IMP FROM #IMP19RED)
	SET @iNICIO = (SELECT TOP 1 INICIO_IMPORTACAO FROM #IMP19RED)
	SET @FIM = (SELECT TOP 1 FIM_IMPORTACAO FROM #IMP19RED)
	SET @DEVOLUCAOCONTRATO = (SELECT TOP 1 CONTRATOS FROM #IMP19RED WHERE DESCRICAO LIKE '%Devolução%')
	SET @DEVOLUCAOPARCELAS = (SELECT TOP 1 PARCELAS FROM #IMP19RED WHERE DESCRICAO LIKE '%Devolução%')


/*CRIAÇÃO DO DESIGNER DA CONSULTA*/

SELECT 'RESUMO DE IMPORTAÇÃO CREDOR: 019 - TIM SERASA ' + '_

		_ARQUIVO: ' + @ARQMOV + '_ 

		_INICIO DA IMPORTAÇÃO: ' + FORMAT(@iNICIO,'dd/mm/yyyy hh:mm','PT-BR') + '_

		_DEVOLUÇÃO DE CONTRATO: ' + CAST(@DEVOLUCAOCONTRATO AS VARCHAR) + '_

		_DEVOLUÇÃO DE PARCELAS: ' + CAST(@DEVOLUCAOPARCELAS AS VARCHAR) + '_

		_FIM DA IMPORTAÇÃO: ' + FORMAT(@FIM,'dd/mm/yyyy hh:mm','PT-BR')

