		/* RELATORIO DE IMP ENTRADA E DEVOLUCAO */
		USE Cobsystems_Base9
			SELECT 
			COUNT(DISTINCT IH.COD_TIT) AS QTD_CONTRATOS,
			CONVERT(VARCHAR(10),I.DATA_IMP, 103) AS DATA_IMP, 
			I.ARQ_IMP, 
			I.COD_IMP,
			S.DESCRICAO
		FROM IMPORTACAO I WITH(NOLOCK)
			INNER JOIN IMPORTACAO_HISTORICO IH WITH(NOLOCK) ON IH.COD_IMP = I.COD_IMP
			INNER JOIN IMPORTACAO_SITUACAO S WITH(NOLOCK) ON S.COD_SITUACAO = IH.COD_SITUACAO
		WHERE I.COD_CRED = 44
		AND ISNULL(I.ARQ_IMP,'') <> ''
		AND I.DATA_IMP BETWEEN CAST(DATEADD(day,0, GETDATE()) AS DATE) AND CAST(GETDATE()+1 AS DATE)
		GROUP BY CONVERT(VARCHAR(10),I.DATA_IMP, 103), I.ARQ_IMP, I.COD_IMP,	S.DESCRICAO
		ORDER BY I.COD_IMP ASC


SELECT DISTINCT V.CPFCGC_PES,
CONVERT(VARCHAR(10),I.DATA_IMP, 103) AS DATA_IMP, 
		I.ARQ_IMP, 
		I.COD_IMP,
		S.DESCRICAO
	--SELECT *
	FROM IMPORTACAO I WITH(NOLOCK)
		INNER JOIN IMPORTACAO_HISTORICO IH WITH(NOLOCK) ON IH.COD_IMP = I.COD_IMP
		INNER JOIN TITULOS T ON T.COD_TIT = IH.COD_TIT
		inner join V_DEVEDORES V ON V.COD_DEV = T.COD_DEV
		INNER JOIN IMPORTACAO_SITUACAO S WITH(NOLOCK) ON S.COD_SITUACAO = IH.COD_SITUACAO
	WHERE I.COD_CRED = 44 AND IH.COD_IMP in (2946444,
2946445,
2946446,
2946447,
2946448,
2946449,
2946450)
	--AND ISNULL(I.ARQ_IMP,'') <> '' 	--AND S.DESCRICAO NOT LIKE '%DEVOLUCAO%'
	ORDER BY I.COD_IMP ASC



	SELECT * FROM REJEICOES_IMPORTACOES
	WHERE COD_IMP in (2396492,
2396492,
2396492,
2396492,
2396498,
2396505,
2396505,
2396505,
2396510,
2396512,
2396512)

	SELECT T.CONTRATO_TIT
FROM TITULOS T WITH(NOLOCK)
			INNER JOIN ULT_OCOR_TIT UT WITH(NOLOCK) ON UT.COD_TIT = T.COD_TIT
			CROSS APPLY (SELECT COUNT (HC.COD_HIST_CLI) AS QTD
FROM HISTORICOS_CLIENTES HC WITH(NOLOCK)
			WHERE DATEDIFF(DD,HC.DATA_CAD,GETDATE()) BETWEEN 0 AND 5 AND HC.USUARIO_CAD IN (1000)
			AND HC.COD_DEV = T.COD_DEV) AS HC
WHERE HC.QTD = 0
			AND T.COD_CRED = 45
			AND UT.ESTAGIO_TIT = 1