--[dbo].[TIM_REMESSA_CONSOLIDADO_20200501_A_20200610_5501_TABULADO]

/* CONTRATOS NO BATIMENTO E NÃO ESTÃO EM ABERTO NA BASE */
USE COBSYSTEMS_BASE8
SELECT count(*) as QTD, 'TIM NÃO ESTÁ NO CRM' FROM  [COBSYSTEMS_DESENV].[DBO].[CARTEIRA_SERVICES_10062020] TMP
	LEFT JOIN 
			(SELECT T.CONTRATO_TIT, D.CPFCGC_PES, T.COD_TIT
			 FROM TITULOS T WITH(NOLOCK) 
			 INNER JOIN V_DEVEDORES D ON D.COD_DEV = T.COd_DEV 
			 INNER JOIN _SOMA_PARC S ON S.COD_TIT = T.COD_TIT
			 WHERE T.COD_CRED = 2) T ON  T.CONTRATO_TIT = [CustCode (DMACCT)] COLLATE Latin1_General_CI_AI AND T.CPFCGC_PES = TMP.[CPF CNPJ (DMSSNUM)] COLLATE Latin1_General_CI_AI
WHERE T.COD_TIT IS NULL
AND TMP.[Agencia (DMAGENCY)] = '5501'


/* ESTÃO NA BASE E NÃO ESTÃO NO ARQUIVO */
SELECT count(*) , 'CRM NÃO ESTÁ NO TIM'  
FROM  
(SELECT T.CONTRATO_TIT, D.CPFCGC_PES, T.COD_TIT
			 FROM TITULOS T WITH(NOLOCK) 
			 INNER JOIN V_DEVEDORES D ON D.COD_DEV = T.COd_DEV 
			 INNER JOIN _SOMA_PARC S ON S.COD_TIT = T.COD_TIT
			 WHERE T.COD_CRED = 2) T
LEFT JOIN [COBSYSTEMS_DESENV].[DBO].[CARTEIRA_SERVICES_10062020] TMP ON  T.CONTRATO_TIT = [CustCode (DMACCT)] COLLATE Latin1_General_CI_AI AND T.CPFCGC_PES = TMP.[CPF CNPJ (DMSSNUM)] COLLATE Latin1_General_CI_AI AND TMP.[Agencia (DMAGENCY)] = '5501'
WHERE TMP. [CustCode (DMACCT)] IS NULL

---------------------------------------------------------------------------------------------------------
--[dbo].[BATIMENTO_TIM_202020612] <<< BATIMENTO

select TOP 1 * from [COBSYSTEMS_DESENV].[dbo].[BATIMENTO_TIM_202020612_TABULADO]
SELECT TOP 1 * FROM [COBSYSTEMS_DESENV].[DBO].[CARTEIRA_SERVICES_10062020] 


/* ESTÃO NA BASE E NÃO ESTÃO NO ARQUIVO */
SELECT COUNT(DISTINCT CONTRATO_TIT),T.NUMERO_ASSESSORIA,T.CRITERIO_CYBER, 'CRM NÃO ESTÁ NO TIM'
--SELECT DISTINCT T.CONTRATO_TIT,T.CPFCGC_PES,
FROM  
(SELECT T.CONTRATO_TIT, D.CPFCGC_PES, T.COD_TIT,AUX.NUMERO_ASSESSORIA,AUX.criterio_cyber
			 FROM TITULOS T WITH(NOLOCK) 
			 INNER JOIN V_DEVEDORES D ON D.COD_DEV = T.COd_DEV 
			 INNER JOIN _SOMA_PARC S ON S.COD_TIT = T.COD_TIT
			 INNER JOIN PARCELAS P WITH(NOLOCK) ON P.COD_TIT = T.COD_TIT AND P.DEVOLVIDO_PARC = 0 AND P.QUITADO_PARC = 0 AND P.PARCELADO_PARC = 0
			 INNER JOIN AUX_TIM_CYBER AUX WITH(NOLOCK) ON AUX.COD_PARC = P.COD_PARC
			 WHERE T.COD_CRED IN (2,10,12)) T
LEFT JOIN [COBSYSTEMS_DESENV].[dbo].[BATIMENTO_TIM_202020612_TABULADO] TMP ON  T.CONTRATO_TIT = TMP.[CODIGO_DO_CLIENTE]
COLLATE Latin1_General_CI_AI AND T.CPFCGC_PES = TMP.[CPF_CPNJ] COLLATE Latin1_General_CI_AI
AND TMP.[NUMERO_DA_ASSESSORIA] IN ('5501','5601','4960')
WHERE TMP.[CODIGO_DO_CLIENTE] IS NULL
GROUP BY T.criterio_cyber,T.numero_assessoria




SELECT TOP 1 * FROM [COBSYSTEMS_DESENV].[dbo].[BATIMENTO_TIM_202020612_TABULADO]


SELECT NUMERO_DA_ASSESSORIA,CRITERIO_DO_CYBER,COUNT(DISTINCT Codigo_do_Cliente) AS [COUNT CustCode]
INTO [COBSYSTEMS_DESENV].[dbo].[BATIMENTO_TIM_202020612_AGRUPADO]
FROM [COBSYSTEMS_DESENV].[dbo].[BATIMENTO_TIM_202020612_TABULADO]
GROUP BY NUMERO_DA_ASSESSORIA,CRITERIO_DO_CYBER
ORDER BY CRITERIO_DO_CYBER ASC

SELECT *,(
	CASE 
		WHEN T2.[COUNT CustCode] IS NOT NULL THEN T1.CUSTCODE - T2.[COUNT CustCode]
		WHEN T2.[COUNT CustCode] IS NULL THEN T1.CUSTCODE
	END
) AS [DIF. CONTRATOS]
SELECT *
FROM COBSYSTEMS_DESENV.DBO.BASE_ATIVA_TIM_002_010_012_20200612 T1
RIGHT JOIN [COBSYSTEMS_DESENV].[dbo].[BATIMENTO_TIM_202020612_AGRUPADO] T2
	ON T2.[CRITERIO_DO_CYBER] = T1.[CRITERIO_CYBER] COLLATE Latin1_General_CI_AI
	AND	T2.[NUMERO_DA_ASSESSORIA] = T1.[NUMERO_ASSESSORIA] COLLATE Latin1_General_CI_AI
ORDER BY T1.NUMERO_ASSESSORIA

SELECT TOP 1 * FROM COBSYSTEMS_DESENV.DBO.BASE_ATIVA_TIM_002_010_012_20200612
SELECT TOP 1 * FROM  COBSYSTEMS_DESENV.DBO.[BATIMENTO_TIM_202020612_TABULADO] 


SELECT COUNT(DISTINCT CPF_CPNJ) FROM COBSYSTEMS_DESENV.DBO.[BATIMENTO_TIM_202020612_TABULADO] 

SELECT DISTINCT T.CONTRATO_TIT
FROM TITULOS T WITH(NOLOCK)
INNER JOIN PARCELAS P WITH(NOLOCK) ON P.COD_TIT = T.COD_TIT
WHERE T.COD_CRED = 2
AND T.CONTRATO_TIT IN (
	SELECT T.CONTRATO_TIT
	FROM TITULOS T WITH(NOLOCK)
	INNER JOIN PARCELAS P WITH(NOLOCK) ON P.COD_TIT = T.COD_TIT
	WHERE T.COD_CRED = 12 
)

--1.31922943              

SELECT TOP 1 * FROM TITULOS T WHERE T.DT_DEVOL_TIT > '2020-06-01 00:00:00'