USE COBSYSTEMS_BASE5
SELECT 
	T.COD_CRED,
	VD.NOME_CRED,
	FILI.NOME_FILI,
	FILI.CODIGO_FILI, 
	COUNT(DISTINCT T.COD_TIT) AS CONTRATOS, 
	COUNT(DISTINCT P.COD_PARC) AS PARCELAS, 
	COUNT(DISTINCT T.COD_DEV) AS DEVEDORES, 
	SUM(P.VR_PARC) AS VALOR
FROM TITULOS T WITH(NOLOCK)
		INNER JOIN PARCELAS P WITH(NOLOCK) ON P.COD_TIT = T.COD_TIT AND P.DEVOLVIDO_PARC = 0 AND P.QUITADO_PARC = 0 
		INNER JOIN V_CREDORES VD WITH(NOLOCK) ON VD.COD_CRED = T.COD_CRED
		INNER JOIN FILIAIS FILI WITH(NOLOCK)  ON FILI.CODIGO_FILI = T.COD_FILI
	WHERE T.COD_CRED IN (50)
GROUP BY T.COD_CRED,VD.NOME_CRED,FILI.NOME_FILI,FILI.CODIGO_FILI