
use Cobsystems_base2
SELECT DISTINCT
T.COD_CRED	,
'16' AS COD_OPERACAO	,
TMP.[CNPJ]  AS CPF_CNPJ	,
'1' AS TIPO_TEL	,
'' AS COD_CREDOR,
LEFT (TMP.[telefone], 2) AS DDD,     -------- NOME DA COLUNA DE TELEFONE
SUBSTRING(TMP.[telefone],4,999999999)AS  NR_TEL,-------- NOME DA COLUNA DE TELEFONE
'8' AS COD_STATUS	,
'N' AS RAMAL	,
'' AS INFOAD_TEL
FROM _SOMA_PARC SP
INNER JOIN TITULOS T WITH(NOLOCK) ON T.COD_TIT = SP.COD_TIT
INNER JOIN  V_DEVEDORES VD WITH(NOLOCK) ON VD.COD_DEV = T.COD_DEV
INNER JOIN VSQL0.SISTEMAS.[DBO].[277_movel] TMP WITH(NOLOCK) ON TMP.[CNPJ] = VD.CPFCGC_PES collate SQL_Latin1_General_CP1_CI_AS

WHERE T.COD_CRED = 277
AND TMP.[CNPJ] !=  ''

--select * from  COBSYSTEMS_DESENV.[DBO].[Base_Celular_15022020] 


--drop table COBSYSTEMS_DESENV.[DBO].[ANALITICO_ACCENTURE_202010]