USE Cobsystems_Base6

	SELECT DATA_IMP, COD_IMP, COD_CRED, ARQ_IMP, DATA_FIM_IMP

		FROM IMPORTACAO

			WHERE COD_CRED =		--INSERIR CÓDIGO DO CREDOR

			--AND ARQ_IMP LIKE'%%'


USE COBSYSTEMS_BASE6

	SELECT CPFCGC_PES AS 'CPF', NR_TEL AS 'TELEFONE', STATUS_TEL AS 'STATUS', COD_CRED AS 'CREDOR'

		FROM PESSOAS_TELEFONES PT

			INNER JOIN TIPOS_TELEFONES TT ON PT.TIPO_TEL = TT.COD_TIP

			INNER JOIN V_DEVEDORES V ON V.COD_PES = PT.COD_PES

				WHERE PT.COD_IMP IN ('')

GROUP BY CPFCGC_PES, NR_TEL, COD_CRED, STATUS_TEL