IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL BEGIN DROP TABLE #TEMP END

SELECT DISTINCT  *,

CASE WHEN DeviceID = 'B:' THEN 'SPEECH'
	 WHEN DeviceID = 'E:' THEN 'VCOM HOMOLOG'
	 WHEN DeviceID = 'J:' THEN 'SISTEMAS 5'
	 WHEN DeviceID = 'K:' THEN 'BACKUP CREDORES'
	 WHEN DeviceID = 'L:' THEN 'SISTEMAS 2'
	 WHEN DeviceID = 'M:' THEN 'CONNECT ATACADAO'
	 WHEN DeviceID = 'N:' THEN 'VCOM SERV11'
	 WHEN DeviceID = 'O:' THEN 'CONNECT DIRECTS'
	 WHEN DeviceID = 'P:' THEN 'SERVICOS 3'
	 WHEN DeviceID = 'Q:' THEN 'VCOM SERV1'
	 WHEN DeviceID = 'R:' THEN 'VCOM SERVIMP2'
	 WHEN DeviceID = 'S:' THEN 'VCOM SERVIMP'
	 WHEN DeviceID = 'T:' THEN 'VCOM SERV9'
	 WHEN DeviceID = 'U:' THEN 'VCOM SERV8'
	 WHEN DeviceID = 'V:' THEN 'VCOM SERV7'
	 WHEN DeviceID = 'W:' THEN 'VCOM SERV4'
	 WHEN DeviceID = 'X:' THEN 'NECTAR2'
	 WHEN DeviceID = 'Y:' THEN 'VCOM SERV6'
	 WHEN DeviceID = 'F:' THEN 'CRM12'
	 WHEN DeviceID = 'G:' THEN 'CRM3'
	 WHEN DeviceID = 'H:' THEN 'CRM1'
	 WHEN DeviceID = 'I:' THEN 'SISTEMAS3'
	 WHEN DeviceID = 'C:' THEN 'SERVICOS4'
	 WHEN DeviceID = 'Z:' THEN 'SISTEMAS1'
	 ELSE '' END  AS NOME_SERVIDORES
FROM TB_SERVIDORES_VOLUMES WHERE UsedSize_Porc > '95%' AND DATE = (SELECT TOP 1 date FROM TB_SERVIDORES_VOLUMES ORDER BY DATE DESC)
 