
SELECT DB_NAME() AS BASE,VC.COD_CRED,VC.NOME_CRED,F.COD_FIL,F.DESC_FIL,F.DATA_INI_APLIC,F.DATA_APLIC
	,DATEDIFF(MINUTE,F.DATA_INI_APLIC,F.DATA_APLIC) AS [TEMPO_MINUTOS]
	,DATEDIFF(SECOND,F.DATA_INI_APLIC,F.DATA_APLIC) AS [TEMPO_SEGUNDOS]
	,COUNT(DISTINCT FT.COD_DEV) AS DEVEDORES
	,COUNT(DISTINCT FT.COD_TIT) AS CONTRATOS
	,(CASE
		WHEN GETDATE() < CAST(CAST(GETDATE() AS DATE) AS VARCHAR) +  ' 21:30:00.000'
		AND DATA_APLIC > CAST(CAST(GETDATE( ) - 1 AS DATE) AS VARCHAR) +  ' 21:30:00.000' THEN 'APLICADO'
		WHEN GETDATE() > CAST(CAST(GETDATE() AS DATE) AS VARCHAR) +  ' 21:30:00.000'
		AND DATA_APLIC > CAST(CAST(GETDATE() AS DATE) AS VARCHAR) +  ' 21:30:00.000' THEN 'APLICADO'
		ELSE 'PENDENTE'
	END) AS STATUS_APLIC
FROM DBO.FILTROS F WITH (NOLOCK)     
	INNER JOIN DBO.FILTROS_COBRANCA FC WITH (NOLOCK) ON (FC.COD_FIL = F.COD_FIL AND FC.COD_TIP = 3) AND F.ATIVO_FIL = 1 AND F.TIP_FIL = 0
	INNER JOIN DBO.V_CREDORES VC ON VC.COD_CRED=FC.VALOR_FC
	LEFT JOIN DBO.FILTROS_TITULOS FT WITH(NOLOCK) ON FT.COD_FIL = F.COD_FIL	
GROUP BY VC.COD_CRED ,VC.NOME_CRED,F.COD_FIL,F.DESC_FIL,F.DATA_INI_APLIC,F.DATA_APLIC