USE COBSYSTEMS_BASE1


SELECT 
	CONVERT(VARCHAR, I.DATA_IMP, 103) AS [DATA IMPORTACAO], I.COD_CRED AS [CREDOR], I.ARQ_IMP AS [ARQUIVO IMPORTADO],
	REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(RI.MSG_REJEICAO,'0',''),'1',''),'2',''),'3',''),'4',''),'5',''),'6',''),'7',''),'8',''),'9','') AS [MSG REJEIÇÃO],
	COUNT(MSG_REJEICAO) QTD
FROM IMPORTACAO I WITH (NOLOCK)
	INNER JOIN REJEICOES_IMPORTACOES RI WITH (NOLOCK) ON RI.COD_IMP = I.COD_IMP
WHERE I.ARQ_IMP IS NOT NULL 
	AND I.DATA_IMP BETWEEN CAST(DATEADD(day,0, GETDATE()) AS DATE) AND CAST(GETDATE()+1 AS DATE)
	AND I.DATA_FIM_IMP IS NOT NULL
	AND RI.MSG_REJEICAO IS NOT NULL
GROUP BY I.DATA_IMP, I.COD_CRED, I.ARQ_IMP, REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(RI.MSG_REJEICAO,'0',''),'1',''),'2',''),'3',''),'4',''),'5',''),'6',''),'7',''),'8',''),'9','')
ORDER BY I.COD_CRED ASC

