use cobsystems_base1
--SELECIONA OS COD_PARC
SELECT T.CONTRATO_TIT, T.COD_TIT, P.COD_PARC, P.NUMERO_PARC, P.QUITADO_PARC, BE.NumeroDocumento, P.COMPL_PARC, PA.DATA_CAD INTO #TMP1 
FROM TITULOS T WITH(NOLOCK)
INNER JOIN PARCELAS P WITH(NOLOCK) ON P.COD_TIT = T.COD_TIT
	AND P.PARCELADO_PARC = 0
INNER JOIN PARCELAMENTOS PA WITH(NOLOCK) ON PA.COD_TIT = T.COD_TIT
INNER JOIN BOLETOS_EM BE WITH(NOLOCK) ON BE.COD_TIT = T.COD_TIT 
	AND BE.DATAVENCIMENTO = P.VCTO_PARC
WHERE T.COD_CRED = 7 AND COMPL_PARC IS NULL

--RODAR DEPOIS DA ANTERIOR
UPDATE 
	PARCELAS
	SET 
	PARCELAS.COMPL_PARC = T.NUMERODOCUMENTO
--SELECT P.COMPL_PARC, T.*
FROM 
PARCELAS P
INNER JOIN #TMP1 T ON T.COD_PARC = P.COD_PARC

