---VERIFICAR VIEW--------
EXEC SP_WHOISACTIVE @FILTER_TYPE = 'DATABASE', @FILTER = 'COBSYSTEMS_BASE8' 

SP_HELPTEXT V_DADOS_TIM_DIGITAL_4 

SELECT TOP 1 * FROM SYS.objects WITH (NOLOCK) WHERE NAME LIKE '%TIM_DIGITAL_2022%'  ORDER BY create_date DESC

SELECT COUNT (*) FROM TIM_DIGITAL_20220607224545_4 WITH (NOLOCK)

--------------IMPORTACAO------------
SELECT TOP 1 FORMAT(GETDATE(),'dd/MM/yyyy','pt-br') AS DATA, COD_IMP,COD_CRED,ARQ_IMP,DATA_IMP,DATA_FIM_IMP, CONVERT(VARCHAR(8),(DATA_FIM_IMP - DATA_IMP),108)[DURACAO_IMP]
	,BATIMENTO,TOT_TITULOS,TOT_PARCELAS,TOT_DEVEDORES
	FROM VSQL10.COBSYSTEMS_BASE8.DBO.IMPORTACAO
	WHERE COD_CRED = 4 
	ORDER BY DATA_IMP DESC 

SELECT * FROM VSQL10.COBSYSTEMS_BASE8.DBO.IMPORTACAO_ETAPA WHERE COD_IMP = 28457 ORDER BY FINALIZADA ASC

-------ESTRATIFICADO------
SELECT
	DT_VENCIMENTO
	,COUNT(DISTINCT CUSTCODE) AS CUSTCODES
	,COUNT(DISTINCT NUM_FATURA) AS FATURAS
	,COUNT(DISTINCT CPF_CNPJ) AS CPF_CNPJ
	,SUM(TRY_CONVERT(MONEY,REPLACE(REPLACE(SALDO_DEVEDOR,',',''),'.','')))/100 AS SALDO_DEVEDOR
FROM Cobsystems_Base8.DBO.TIM_DIGITAL_20220720190729_4 WITH(NOLOCK)  
GROUP BY DT_VENCIMENTO
ORDER BY DT_VENCIMENTO ASC


----EXTRATIFICADO CARTEIRA------
SELECT
	DT_VENCIMENTO
	,COUNT(DISTINCT CUSTCODE) AS CUSTCODES
	,COUNT(DISTINCT NUM_FATURA) AS FATURAS
	,COUNT(DISTINCT CPF_CNPJ) AS CPF_CNPJ
	,SUM(CONVERT(MONEY,REPLACE(REPLACE(SALDO_DEVEDOR,',',''),'.','')))/100 AS SALDO_DEVEDOR
FROM Cobsystems_Base8.DBO.TIM_DIGITAL_20220720190729_4 WITH(NOLOCK)  
WHERE DESCONTO_REMCAMP IS NOT NULL
GROUP BY DT_VENCIMENTO


-------_ANALITICO_UPLOAD_-------------

SELECT
	CPF_CNPJ,NOM_CLIENTE,CUSTCODE,NUM_FATURA,DT_VENCIMENTO,SALDO_DEVEDOR,GSM_RP,ENDERECO_CLIENTE,NUMERO_ENDERECO
	,COMPLEMENTO_ENDERECO,BAIRRO,CIDADE,CEP,UF,COD_BARRA,DESCONTO,CUSTOMER_ID,ASSESSORIA,CRIT_CYBER,COD_BARRAS_REMCAMP
	,DESCONTO_REMCAMP,DT_VALIDADE_CAMP,DT_NASC
	,(SELECT MAX(MODIFY_DATE) FROM sys.objects WHERE NAME LIKE 'TIM_DIGITAL_%') AS DATA_UPLOAD
	,'OK' AS STATUS_UPLOAD
FROM Cobsystems_Base8.DBO.TIM_DIGITAL_20220720190729_4 WITH(NOLOCK)  